# Generated by Django 4.2.11 on 2024-07-24 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
